### ISSUE TITLE
getStatuses - we need to have more pleasant way to reach properties

### ISSUE THREAD

**Issue by netlooker** [ec-europa/oe-poetry-client#50]
We need to get the statuses properites in a better way than
$response->getStatuses()[0]->getCode().

My proposal is to use something like this:
$response->getStatuses()->getDemandStatus()->getCode() 
$response->getStatuses()->getRequestStatus()->getCode()

**Comment by ademarco** [comment]
I'm on it.

**Comment by ademarco** [comment]
We will actually have the request methods directly on the request object, as shown below, and we will assume that we only have one demand and one request status, for now:

```php
$response->getDemandStatus()->getCode()
$response->getRequestStatus()->getCode()
```

Is that ok @netlooker ?

**Comment by ademarco** [comment]
Ok issue ready for review.

@netlooker please check if provided API matches this issue's acceptance criteria by reviewing this [documentation page](https://github.com/ec-europa/oe-poetry-client/blob/72d7141fffb180e23216907018bb53fc115e0858/docs/02-messages.md#working-with-status-responses)

**Comment by netlooker** [comment]
Sounds good and for me, that's how I've understood the documentation.
