### ISSUE TITLE
Create basic SOAP client and server

### ISSUE THREAD

**Issue by imanoleguskiza** [ec-europa/oe-poetry-client#6]
Create SOAP client service.
The SOAP client needs the following parameters:
- user
- password
- message

The SOAP client will:

- Validate the message and its components throwing an exception if a problem occurs 
-  Render the message 
-  Perform a SOAP request to the Poetry Service. 

Also create a basic Soap server with dependency injection.

**Comment by ademarco** [comment]
Work happening on branch `6-soapclient`
